# Generated by Django 5.0.7 on 2024-07-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='meaasge',
            new_name='message',
        ),
    ]
